# Generated by Django 4.1.4 on 2023-02-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_demo_link_alter_project_source_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="vote_ratio",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="vote_total",
            field=models.IntegerField(default=0),
        ),
    ]
