# Generated by Django 4.1.4 on 2023-02-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_alter_project_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="default.jpeg", null=True, upload_to=""
            ),
        ),
    ]
