# Generated by Django 4.1.4 on 2023-02-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_tag_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="value",
            field=models.CharField(
                choices=[("up", "up"), ("down", "down")], max_length=50
            ),
        ),
    ]
