# Generated by Django 4.1.4 on 2023-02-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_review_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
